name: "build proxy-balancer On PR approve / merge to dev and master"

on:
  pull_request_review:
    types: [submitted]
    paths:
      - "proxy-balancer.conf"
      - ".github/workflows/proxy-balancer*"
      - ".docker/Dockerfile.proxy-balancer*"
      - "packages/**"
  push:
    branches: [master]
    paths:
      - "proxy-balancer.conf"
      - ".github/workflows/proxy-balancer*"
      - ".docker/Dockerfile.proxy-balancer*"
      - "packages/**"

jobs:
  proxy-balancer-build-and-publish-latest:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # Running this job only for master branch

    steps:
      - uses: actions/checkout@v3 # Checking out the repo

      - name: Build and Publish latest Docker image
        uses: VaultVulp/gp-docker-action@1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
          image-name: proxy-balancer # Provide only Docker image name, tag will be automatically set to latest
          dockerfile: .docker/Dockerfile.proxy-balancer
  proxy-balancer-build-and-publish-tag:
    runs-on: ubuntu-latest
    if: (github.ref != 'refs/heads/master') && (github.ref != 'refs/heads/develop') && (github.event.review.state == 'approved') # Running this job only for master and develop branch

    steps:
      - uses: actions/checkout@v3

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Build and Publish Tag Docker image
        uses: VaultVulp/gp-docker-action@1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
          image-name: proxy-balancer # Provide only Docker image name
          dockerfile: .docker/Dockerfile.proxy-balancer
          image-tag: ${{ steps.extract_branch.outputs.branch }}
